language: python

python: 
  - "3.6.6"
services:
  - postgresql
env:
  global:
    - DB_NAME='test_db'

install:
  - "pip install -r requirements.txt"

before script:
  - "psql -c 'create database test_db;' -U postgres"

script:
  - python3 -m pytest --cov
  
after_success:
  - coveralls